[ip.replace.src]
"172\\.19\\.[1-5]{1-3}\\.[0-9]{1-3}" = "192.168.130.45"
"172\\.19\\.[6-9]{1-3}\\.[0-9]{1-3}" = "192.168.130.19"
"172\\.19\\.1[0-4]{1-2}\\.[0-9]{1-3}" = "192.168.130.20"
"172\\.19\\.1[5-1]{1-2}\\.[0-9]{1-3}" = "192.168.130.142"
"172\\.19\\.2[0-2]{1-2}\\.[0-9]{1-3}" =  "192.168.130.142"

[ip.delete.src]
0 = "192\\.168\\.130\\.1"

[ip.replace.dst]

[ip.delete.dst]

[pcap.files]
"normal_dt-small.pcap.old" = "normal-dt-small.pcap"
"attack_dt-small.pcap.old" = "attack-dt-small.pcap"
"attack_dt-large.pcap.old" = "attack-dt-large.pcap"
