[ip.replace.src]
"^172\\.19\\.[0-5]\\.[0-9][0-9][0-9]$" = "192.168.130.45"
"172\\.19\\.[6-9]\\.[0-9][0-9][0-9]" = "192.168.130.19"
"172\\.19\\.1[0-4]\\.[0-9][0-9][0-9]" = "192.168.130.20"
"172\\.19\\.1[5-9]\\.[0-9][0-9][0-9]" = "192.168.130.142"
"172\\.19\\.2[0-2]\\.[0-9][0-9][0-9]" =  "192.168.130.142"

[ip.replace.dst]

[ip.delete.src]
0 = "192\\.168\\.130\\.1"

[ip.delete.dst]

[pcap.files]
"/mnt/c/Users/alexcarrega/Downloads/normal_dt-small.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/normal-dt-small.pcap"
"/mnt/c/Users/alexcarrega/Downloads/attack_dt-small.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/attack-dt-small.pcap"
"/mnt/c/Users/alexcarrega/Downloads/attack_dt-large.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/attack-dt-large.pcap"
