[ip.replace.src.target]
0 = "^172\\.19\\.[0-5]\\.[0-9]$"
1 = "^172\\.19\\.[0-5]\\.[0-9][0-9]$"
2 = "^172\\.19\\.[0-5]\\.[0-9][0-9][0-9]$"
3 = "^172\\.19\\.[6-9]\\.[0-9]$"
4 = "^172\\.19\\.[6-9]\\.[0-9][0-9]$"
5 = "^172\\.19\\.[6-9]\\.[0-9][0-9][0-9]$"
6 = "^172\\.19\\.1[0-4]\\.[0-9]$"
7 = "^172\\.19\\.1[0-4]\\.[0-9][0-9]$"
8 = "^172\\.19\\.1[0-4]\\.[0-9][0-9][0-9]$"
9 = "^172\\.19\\.1[5-9]\\.[0-9]$"
10 = "^172\\.19\\.1[5-9]\\.[0-9][0-9]$"
11 = "^172\\.19\\.1[5-9]\\.[0-9][0-9][0-9]$"
12 = "^172\\.19\\.2[0-2]\\.[0-9]$"
13 = "^172\\.19\\.2[0-2]\\.[0-9][0-9]$"
14 = "^172\\.19\\.2[0-2]\\.[0-9][0-9][0-9]$"

[ip.replace.src.random]
0 = "192.168.130.45"
1 = "192.168.130.20"
2 = "192.168.130.142"
3 = "192.168.130.19"

[ip.replace.dst.target]

[ip.replace.dst.random]

[ip.delete.src]
0 = "^192\\.168\\.130\\.9$"

[ip.delete.dst]

[pcap.files]
# "/mnt/c/Users/alexcarrega/Downloads/normal_dt-small.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/normal_dt-small.pcap"
# "/mnt/c/Users/alexcarrega/Downloads/attack_dt-small.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/attack_dt-small.pcap"
"/mnt/c/Users/alexcarrega/Downloads/normal_dt-large.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/normal_dt-large.pcap"
