[ip.replace.src.target]
0 = "^172\\.19\\..*$"
4 = "^185\\..*$"

[ip.replace.src.random]
0 = "10.250.237.145"
1 = "10.250.237.144"
2 = "10.250.237.146"
3 = "10.250.237.147"
4 = "10.250.237.148"
5 = "10.250.237.149"
6 = "10.250.237.150"
7 = "10.250.237.127"
8 = "10.250.237.129"
9 = "10.250.237.128"

[ip.replace.dst.target]
0 = "^192\\.168\\.130\\.9$"
1 = "^172\\.19\\..*$"
2 = "^185\\..*$"

[ip.replace.dst.random]
0 = "192.168.130.45"
1 = "192.168.130.9"
2 = "192.168.130.20"
3 = "192.168.130.142"
4 = "192.168.130.19"

[ip.delete.src]

[ip.delete.dst]

[ip.reply_last.src]
0 = "^192\\.168\\.130\\.9$"

[ip.reply_last.dst]

[pcap.files]
"/mnt/c/Users/alexcarrega/Downloads/normal_dt-small.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/normal_dt-small-b.pcap"
"/mnt/c/Users/alexcarrega/Downloads/attack_dt-small.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/attack_dt-small-b.pcap"
"/mnt/c/Users/alexcarrega/Downloads/normal_dt-large.pcap.old" = "/mnt/c/Users/alexcarrega/Downloads/normal_dt-large-b.pcap"
# "/home/alexcarrega/Downloads/normal_dt-small.pcap.old" = "/home/alexcarrega/Downloads/normal_dt-small.pcap"
# "/home/alexcarrega/Downloads/attack_dt-small.pcap.old" = "/home/alexcarrega/Downloads/attack_dt-small.pcap"
# "/home/alexcarrega/Downloads/normal_dt-large.pcap.old" = "/home/alexcarrega/Downloads/normal_dt-large.pcap"
